name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Build Flutter Web
      - run: flutter pub get
      - run: flutter build web --release

      # 4. Deploy to Firebase Hosting (con action que ya trae firebase-tools)
      - uses: w9jds/firebase-action@v13.24.0
        with:
          args: deploy --only hosting --project portfolio-51983
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
