name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Build Flutter Web
      - run: flutter pub get
      - run: flutter build web --release

      # 4. Install Firebase CLI
      - run: npm install -g firebase-tools
      - run: firebase --version

      # 5. Deploy to Firebase Hosting
      - run: firebase deploy --only hosting --project portfolio-51983 --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
